### ISSUE TITLE
Quote key defined in numlock layer, LED lit when layer is active

### ISSUE THREAD

**Issue by ImmaculatePotato** [keyboardio/Model01-Firmware#48]
Per Eddie Jinks' 2017-11-15 post on the community site (apologies if I'm overlooking some aspect of github etiquette):

> Random observation today while I was working and getting used to using NumLock to access the number pad more quickly… The quote key (2 spaces down from the num key) lights up red. I looked at the default legend that comes with the Model 01 and noticed that that key doesn’t have a NumLock assignment.
> 
> Through just a little digging, I found that this is due to the fact that the NumLock layer has Key_Quote assigned to that key and doesn’t just fall through to the base layer (also defined as Key_Quote). Was this intentional? Maybe we should just update the default sketch to have that key be transparent so it doesn’t light up red and confuse people.

**Comment by algernon** [comment]
Good catch. It should, indeed, be a transparent key.
