### ISSUE TITLE
make flash doesn't work

### ISSUE THREAD

**Issue by wt** [keyboardio/Model01-Firmware#54]
I am on linux with an arduino ide I just downloaded. I am sync'd to the latest master (c7fab58f63b99013baa89b6637f36ad7be3bb3bc).
It will not build. Here's some output to help:

```
$ make flash
BOARD_HARDWARE_PATH="/home/wt/Arduino/hardware" /home/wt/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope/bin//kaleidoscope-builder flash
Building output/Model01-Firmware/Model01-Firmware (0.0.0-gv1.22-13-gc7fa) ...
/home/wt/Arduino/Model01-Firmware/Model01-Firmware.ino:285:26: error: expected constructor, destructor, or type conversion before '(' token
 KALEIDOSCOPE_INIT_PLUGINS(
                          ^
exit status 1
/home/wt/Arduino/hardware/keyboardio/avr/build-tools/makefiles//rules.mk:72: recipe for target 'flash' failed
make: *** [flash] Error 1
```

**Comment by obra** [comment]
Hi Wren,

Are you also current on the Arduino-Boards repo? Once you pull that one,
you also need to 'make update-submodules' inside it.

Best,
Jesse

**Comment by obra** [comment]
I'm closing this for now due to the lack of a reply. Feel free to reopen it if you still need a hand, @wt.

**Comment by wt** [comment]
I figured it out. I don't remember what I did.
