### ISSUE TITLE
curly braces sometimes type square braces

### ISSUE THREAD

**Issue by DavidVentura** [keyboardio/Model01-Firmware#61]
hello 
on my default model01 firmware this is what happens if I hold fn and tap the U key

```
[[{{[{{{{[{{[{[{{{[{{{{{{{{[[{{{{[[{[
```

and tapping UI 
```
{}{}{}[]{}{}[][]{}{}{}{}{}[][][]{}[]{}{}[][]
```

what's going on?

**Comment by obra** [comment]
I believe I've got the fix for this and should be able to get a new
firmware source code release out this weekend for you to try.

Best,
Jesse
ᐧ

**Comment by DavidVentura** [comment]
I would like to note that this only happens on my work pc.. not on my home desktop.

**Comment by obra** [comment]
Noted. It's a weird sort of USB timing issue that can be pretty variable
depending on the computer's exact OS version.

Best,
Jesse
ᐧ
