### ISSUE TITLE
Model01-Firmware doesn't seem to be in sync with the plugins anymore?

### ISSUE THREAD

**Issue by milkypostman** [keyboardio/Model01-Firmware#66]
Just pulled the latest Model01-Firmware and it's clearly out of date with the plugins. Foremost is that `Kaleidoscope-Focus` is linked in as `Kaleidoscope-FocusSerial`.

Should I be switching to using the straight up `Kaleidoscope` firmware?

**Comment by milkypostman** [comment]
so, i see what you're doing now by bundling things into a single repo. I think this is super smart. anyways i'll close this as it's only a distraction.

**Comment by obra** [comment]
Thanks for the prod. I've gone and archived the Arduino-Boards repository,
which I suspect was the cause of a bunch of this sort of problem.
ᐧ
